import { useState, useMemo } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { 
  getLifePath, 
  getDayNumber, 
  getMonthNumber, 
  getVietnamAnimal,
  getPersonalYear,
  getPersonalMonth,
  getPersonalDay,
  getUniversalYear,
  numberMeanings,
  animalFriends,
  animalEnemiesPrimary,
  animalEnemiesSecondary,
  getReportTemplate,
  getDailyForecast
} from "@/lib/numerology";
import { Copy, Download, FileText, Check } from "lucide-react";
import { format } from "date-fns";

interface ExportPanelProps {
  name: string;
  dob: Date;
}

export function ExportPanel({ name, dob }: ExportPanelProps) {
  const [copied, setCopied] = useState(false);

  const report = useMemo(() => {
    const lp = getLifePath(dob);
    const dayNum = getDayNumber(dob);
    const monthNum = getMonthNumber(dob);
    const animal = getVietnamAnimal(dob.getFullYear(), dob);
    const uy = getUniversalYear();
    const py = getPersonalYear(dob);
    const pm = getPersonalMonth(dob);
    const pd = getPersonalDay(dob);
    const forecast = getDailyForecast(pd);
    const template = getReportTemplate(lp.lifePath, dayNum, monthNum);

    const lpMeaning = numberMeanings[lp.lifePath];
    const dayMeaning = numberMeanings[dayNum];
    const monthMeaning = numberMeanings[monthNum];

    const friends = animalFriends[animal] || [];
    const enemiesPrimary = animalEnemiesPrimary[animal] || [];
    const enemiesSecondary = animalEnemiesSecondary[animal] || [];

    let text = `
================================================================================
                        THE UNIVERSAL MATRIX
                     Numerology Report for ${name}
================================================================================

Generated: ${format(new Date(), "MMMM d, yyyy 'at' h:mm a")}
Date of Birth: ${format(dob, "MMMM d, yyyy")}

================================================================================
                           CORE NUMBERS
================================================================================

LIFE PATH: ${lp.lifePath}
${lpMeaning.core}
${lpMeaning.essence}

DAY NUMBER: ${dayNum}
${dayMeaning.core}
Your outer expression and how you appear to the world.

MONTH NUMBER: ${monthNum}
${monthMeaning.core}
Your life arena and recurring themes.

================================================================================
                         PERSONAL CYCLES
================================================================================

Universal Year: ${uy}
Personal Year: ${py}
Personal Month: ${pm}
Personal Day: ${pd}

TODAY'S FORECAST:
${forecast}

================================================================================
                       VIETNAMESE ZODIAC
================================================================================

Animal Sign: ${animal}
Birth Year: ${dob.getFullYear()}

Natural Allies: ${friends.join(", ")}
Primary Clash: ${enemiesPrimary.join(", ")}
Secondary Tension: ${enemiesSecondary.join(", ")}

================================================================================
                         DETAILED ANALYSIS
================================================================================

LIFE PATH ${lp.lifePath} - ${lpMeaning.core}

Strengths:
${lpMeaning.strengths.map(s => `  - ${s}`).join("\n")}

Shadow Traits:
${lpMeaning.traps.map(t => `  - ${t}`).join("\n")}

Money Patterns:
${lpMeaning.money.map(m => `  - ${m}`).join("\n")}

Relationships:
${lpMeaning.relationships.map(r => `  - ${r}`).join("\n")}

Shadow Work:
${lpMeaning.shadowWork}

Career Suggestions:
${lpMeaning.careers.join(", ")}
`;

    if (template) {
      text += `
================================================================================
                      YOUR ARCHETYPE: ${template.name}
================================================================================

${template.archetype}

${template.summary}

Key Insights:
${template.keyInsights.map(i => `  - ${i}`).join("\n")}
`;
    }

    text += `
================================================================================
                            END OF REPORT
================================================================================

Report generated by The Universal Matrix
`;

    return text.trim();
  }, [name, dob]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `universal-matrix-${name.toLowerCase().replace(/\s+/g, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Export Full Report
        </CardTitle>
        <p className="text-sm text-muted-foreground">
          Copy or download your complete numerology analysis
        </p>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex items-center gap-2 flex-wrap">
          <Badge variant="secondary">
            {report.split("\n").length} lines
          </Badge>
          <Badge variant="secondary">
            {report.length.toLocaleString()} characters
          </Badge>
        </div>

        <Textarea
          value={report}
          readOnly
          className="min-h-[400px] font-mono text-xs"
          data-testid="textarea-export"
        />

        <div className="flex gap-3 flex-wrap">
          <Button onClick={handleCopy} variant="outline" data-testid="button-copy">
            {copied ? (
              <>
                <Check className="mr-2 h-4 w-4" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="mr-2 h-4 w-4" />
                Copy to Clipboard
              </>
            )}
          </Button>
          <Button onClick={handleDownload} data-testid="button-download">
            <Download className="mr-2 h-4 w-4" />
            Download TXT
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
